package at.easydiet.model;
// Generated 06.04.2011 14:32:00 by Hibernate Tools 3.4.0.CR1


import java.sql.Clob;
import java.util.Date;

/**
 * ContactJournal generated by hbm2java
 */
public class ContactJournal  implements java.io.Serializable {


     private long contactJournalId;
     private Date date;
     private Clob description;
     private SystemUser createdBy;
     private ContactType contactType;

    public ContactJournal() {
    }

	
    public ContactJournal(Date date, SystemUser createdBy, ContactType contactType) {
        this.date = date;
        this.createdBy = createdBy;
        this.contactType = contactType;
    }
    public ContactJournal(Date date, Clob description, SystemUser createdBy, ContactType contactType) {
       this.date = date;
       this.description = description;
       this.createdBy = createdBy;
       this.contactType = contactType;
    }
   
    public long getContactJournalId() {
        return this.contactJournalId;
    }
    
    public void setContactJournalId(long contactJournalId) {
        this.contactJournalId = contactJournalId;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Clob getDescription() {
        return this.description;
    }
    
    public void setDescription(Clob description) {
        this.description = description;
    }
    public SystemUser getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(SystemUser createdBy) {
        this.createdBy = createdBy;
    }
    public ContactType getContactType() {
        return this.contactType;
    }
    
    public void setContactType(ContactType contactType) {
        this.contactType = contactType;
    }




}


