package at.easydiet.model;
// Generated 06.04.2011 16:43:36 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DietTreatment generated by hbm2java
 */
public class DietTreatment  implements java.io.Serializable {


     private long dietTreatmentId;
     private Date start;
     private int duration;
     private String name;
     private Set<NutritionProtocol> nutritionProtocols = new HashSet<NutritionProtocol>(0);
     private Set<DietPlan> dietPlans = new HashSet<DietPlan>(0);
     private Set<DietParameter> dietParameters = new HashSet<DietParameter>(0);
     private Set<PatientState> patientStates = new HashSet<PatientState>(0);
     private Set<DietTreatmentSystemUser> systemUsers = new HashSet<DietTreatmentSystemUser>(0);
     private Set<ContactJournal> contactJournals = new HashSet<ContactJournal>(0);
     private TreatmentState treatmentState;

    public DietTreatment() {
    }

	
    public DietTreatment(Date start, int duration, String name, TreatmentState treatmentState) {
        this.start = start;
        this.duration = duration;
        this.name = name;
        this.treatmentState = treatmentState;
    }
    public DietTreatment(Date start, int duration, String name, Set<NutritionProtocol> nutritionProtocols, Set<DietPlan> dietPlans, Set<DietParameter> dietParameters, Set<PatientState> patientStates, Set<DietTreatmentSystemUser> systemUsers, Set<ContactJournal> contactJournals, TreatmentState treatmentState) {
       this.start = start;
       this.duration = duration;
       this.name = name;
       this.nutritionProtocols = nutritionProtocols;
       this.dietPlans = dietPlans;
       this.dietParameters = dietParameters;
       this.patientStates = patientStates;
       this.systemUsers = systemUsers;
       this.contactJournals = contactJournals;
       this.treatmentState = treatmentState;
    }
   
    public long getDietTreatmentId() {
        return this.dietTreatmentId;
    }
    
    public void setDietTreatmentId(long dietTreatmentId) {
        this.dietTreatmentId = dietTreatmentId;
    }
    public Date getStart() {
        return this.start;
    }
    
    public void setStart(Date start) {
        this.start = start;
    }
    public int getDuration() {
        return this.duration;
    }
    
    public void setDuration(int duration) {
        this.duration = duration;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<NutritionProtocol> getNutritionProtocols() {
        return this.nutritionProtocols;
    }
    
    public void setNutritionProtocols(Set<NutritionProtocol> nutritionProtocols) {
        this.nutritionProtocols = nutritionProtocols;
    }
    public Set<DietPlan> getDietPlans() {
        return this.dietPlans;
    }
    
    public void setDietPlans(Set<DietPlan> dietPlans) {
        this.dietPlans = dietPlans;
    }
    public Set<DietParameter> getDietParameters() {
        return this.dietParameters;
    }
    
    public void setDietParameters(Set<DietParameter> dietParameters) {
        this.dietParameters = dietParameters;
    }
    public Set<PatientState> getPatientStates() {
        return this.patientStates;
    }
    
    public void setPatientStates(Set<PatientState> patientStates) {
        this.patientStates = patientStates;
    }
    public Set<DietTreatmentSystemUser> getSystemUsers() {
        return this.systemUsers;
    }
    
    public void setSystemUsers(Set<DietTreatmentSystemUser> systemUsers) {
        this.systemUsers = systemUsers;
    }
    public Set<ContactJournal> getContactJournals() {
        return this.contactJournals;
    }
    
    public void setContactJournals(Set<ContactJournal> contactJournals) {
        this.contactJournals = contactJournals;
    }
    public TreatmentState getTreatmentState() {
        return this.treatmentState;
    }
    
    public void setTreatmentState(TreatmentState treatmentState) {
        this.treatmentState = treatmentState;
    }




}


