package at.easydiet.model;
// Generated 06.04.2011 16:43:36 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DietPlan generated by hbm2java
 */
public class DietPlan  implements java.io.Serializable {


     private long dietPlanId;
     private String name;
     private Date createdOn;
     private PlanType planType;
     private Set<DietParameter> dietParameters = new HashSet<DietParameter>(0);
     private SystemUser creator;
     private Set<TimeSpan> timeSpans = new HashSet<TimeSpan>(0);

    public DietPlan() {
    }

	
    public DietPlan(String name, Date createdOn, PlanType planType, SystemUser creator) {
        this.name = name;
        this.createdOn = createdOn;
        this.planType = planType;
        this.creator = creator;
    }
    public DietPlan(String name, Date createdOn, PlanType planType, Set<DietParameter> dietParameters, SystemUser creator, Set<TimeSpan> timeSpans) {
       this.name = name;
       this.createdOn = createdOn;
       this.planType = planType;
       this.dietParameters = dietParameters;
       this.creator = creator;
       this.timeSpans = timeSpans;
    }
   
    public long getDietPlanId() {
        return this.dietPlanId;
    }
    
    public void setDietPlanId(long dietPlanId) {
        this.dietPlanId = dietPlanId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }
    public PlanType getPlanType() {
        return this.planType;
    }
    
    public void setPlanType(PlanType planType) {
        this.planType = planType;
    }
    public Set<DietParameter> getDietParameters() {
        return this.dietParameters;
    }
    
    public void setDietParameters(Set<DietParameter> dietParameters) {
        this.dietParameters = dietParameters;
    }
    public SystemUser getCreator() {
        return this.creator;
    }
    
    public void setCreator(SystemUser creator) {
        this.creator = creator;
    }
    public Set<TimeSpan> getTimeSpans() {
        return this.timeSpans;
    }
    
    public void setTimeSpans(Set<TimeSpan> timeSpans) {
        this.timeSpans = timeSpans;
    }


    /**
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode()
    {
        final int prime = 31;
        int result = 1;
        result = prime * result
                + ((createdOn == null) ? 0 : createdOn.hashCode());
        result = prime * result + ((creator == null) ? 0 : creator.hashCode());
        result = prime * result
                + ((dietParameters == null) ? 0 : dietParameters.hashCode());
        result = prime * result + (int) (dietPlanId ^ (dietPlanId >>> 32));
        result = prime * result + ((name == null) ? 0 : name.hashCode());
        result = prime * result
                + ((planType == null) ? 0 : planType.hashCode());
        result = prime * result
                + ((timeSpans == null) ? 0 : timeSpans.hashCode());
        return result;
    }

    /**
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj)
    {
        if (this == obj) return true;
        if (obj == null) return false;
        if (!(obj instanceof DietPlan)) return false;
        DietPlan other = (DietPlan) obj;
        if (createdOn == null)
        {
            if (other.createdOn != null) return false;
        }
        else if (!createdOn.equals(other.createdOn)) return false;
        if (creator == null)
        {
            if (other.creator != null) return false;
        }
        else if (!creator.equals(other.creator)) return false;
        if (dietParameters == null)
        {
            if (other.dietParameters != null) return false;
        }
        else if (!dietParameters.equals(other.dietParameters)) return false;
        if (dietPlanId != other.dietPlanId) return false;
        if (name == null)
        {
            if (other.name != null) return false;
        }
        else if (!name.equals(other.name)) return false;
        if (planType == null)
        {
            if (other.planType != null) return false;
        }
        else if (!planType.equals(other.planType)) return false;
        if (timeSpans == null)
        {
            if (other.timeSpans != null) return false;
        }
        else if (!timeSpans.equals(other.timeSpans)) return false;
        return true;
    }




}


