package at.easydiet.model;
// Generated 06.04.2011 14:32:00 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DietPlan generated by hbm2java
 */
public class DietPlan  implements java.io.Serializable {


     private long dietPlanId;
     private String name;
     private Date createdOn;
     private PlanType planType;
     private Set<DietParameter> dietParameters = new HashSet<DietParameter>(0);
     private SystemUser creator;
     private Set<TimeSpan> timeSpans = new HashSet<TimeSpan>(0);

    public DietPlan() {
    }

	
    public DietPlan(String name, Date createdOn, PlanType planType, SystemUser creator) {
        this.name = name;
        this.createdOn = createdOn;
        this.planType = planType;
        this.creator = creator;
    }
    public DietPlan(String name, Date createdOn, PlanType planType, Set<DietParameter> dietParameters, SystemUser creator, Set<TimeSpan> timeSpans) {
       this.name = name;
       this.createdOn = createdOn;
       this.planType = planType;
       this.dietParameters = dietParameters;
       this.creator = creator;
       this.timeSpans = timeSpans;
    }
   
    public long getDietPlanId() {
        return this.dietPlanId;
    }
    
    public void setDietPlanId(long dietPlanId) {
        this.dietPlanId = dietPlanId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }
    public PlanType getPlanType() {
        return this.planType;
    }
    
    public void setPlanType(PlanType planType) {
        this.planType = planType;
    }
    public Set<DietParameter> getDietParameters() {
        return this.dietParameters;
    }
    
    public void setDietParameters(Set<DietParameter> dietParameters) {
        this.dietParameters = dietParameters;
    }
    public SystemUser getCreator() {
        return this.creator;
    }
    
    public void setCreator(SystemUser creator) {
        this.creator = creator;
    }
    public Set<TimeSpan> getTimeSpans() {
        return this.timeSpans;
    }
    
    public void setTimeSpans(Set<TimeSpan> timeSpans) {
        this.timeSpans = timeSpans;
    }




}


