package at.easydiet.model;
// Generated 06.04.2011 14:32:00 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * DietParameterSet generated by hbm2java
 */
public class DietParameterSet  implements java.io.Serializable {


     private long dietParameterSetId;
     private String name;
     private Set<DietParameterTemplate> dietParameterTemplates = new HashSet<DietParameterTemplate>(0);

    public DietParameterSet() {
    }

	
    public DietParameterSet(String name) {
        this.name = name;
    }
    public DietParameterSet(String name, Set<DietParameterTemplate> dietParameterTemplates) {
       this.name = name;
       this.dietParameterTemplates = dietParameterTemplates;
    }
   
    public long getDietParameterSetId() {
        return this.dietParameterSetId;
    }
    
    public void setDietParameterSetId(long dietParameterSetId) {
        this.dietParameterSetId = dietParameterSetId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<DietParameterTemplate> getDietParameterTemplates() {
        return this.dietParameterTemplates;
    }
    
    public void setDietParameterTemplates(Set<DietParameterTemplate> dietParameterTemplates) {
        this.dietParameterTemplates = dietParameterTemplates;
    }




}


