package at.easydiet.model;
// Generated 06.04.2011 16:43:36 by Hibernate Tools 3.4.0.CR1



/**
 * FamilyAnamnesis generated by hbm2java
 */
public class FamilyAnamnesis  implements java.io.Serializable {


     private long familyAnamnesisId;
     private String person;
     private String[] illnesses;

    public FamilyAnamnesis() {
    }

	
    public FamilyAnamnesis(String person) {
        this.person = person;
    }
    public FamilyAnamnesis(String person, String[] illnesses) {
       this.person = person;
       this.illnesses = illnesses;
    }
   
    public long getFamilyAnamnesisId() {
        return this.familyAnamnesisId;
    }
    
    public void setFamilyAnamnesisId(long familyAnamnesisId) {
        this.familyAnamnesisId = familyAnamnesisId;
    }
    public String getPerson() {
        return this.person;
    }
    
    public void setPerson(String person) {
        this.person = person;
    }
    public String[] getIllnesses() {
        return this.illnesses;
    }
    
    public void setIllnesses(String[] illnesses) {
        this.illnesses = illnesses;
    }




}


