package at.easydiet.model;
// Generated 06.04.2011 14:32:00 by Hibernate Tools 3.4.0.CR1


import java.sql.Clob;
import java.util.HashSet;
import java.util.Set;

/**
 * MealLine generated by hbm2java
 */
public class MealLine  implements java.io.Serializable {


     private long mealLineId;
     private float quantity;
     private Clob info;
     private boolean add;
     private Set<MealLine> mealLines = new HashSet<MealLine>(0);
     private Recipe recipe;

    public MealLine() {
    }

	
    public MealLine(float quantity, boolean add, Recipe recipe) {
        this.quantity = quantity;
        this.add = add;
        this.recipe = recipe;
    }
    public MealLine(float quantity, Clob info, boolean add, Set<MealLine> mealLines, Recipe recipe) {
       this.quantity = quantity;
       this.info = info;
       this.add = add;
       this.mealLines = mealLines;
       this.recipe = recipe;
    }
   
    public long getMealLineId() {
        return this.mealLineId;
    }
    
    public void setMealLineId(long mealLineId) {
        this.mealLineId = mealLineId;
    }
    public float getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(float quantity) {
        this.quantity = quantity;
    }
    public Clob getInfo() {
        return this.info;
    }
    
    public void setInfo(Clob info) {
        this.info = info;
    }
    public boolean isAdd() {
        return this.add;
    }
    
    public void setAdd(boolean add) {
        this.add = add;
    }
    public Set<MealLine> getMealLines() {
        return this.mealLines;
    }
    
    public void setMealLines(Set<MealLine> mealLines) {
        this.mealLines = mealLines;
    }
    public Recipe getRecipe() {
        return this.recipe;
    }
    
    public void setRecipe(Recipe recipe) {
        this.recipe = recipe;
    }




}


