package at.easydiet.model;
// Generated 06.04.2011 14:32:00 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * Meal generated by hbm2java
 */
public class Meal  implements java.io.Serializable {


     private long mealId;
     private String code;
     private String name;
     private Set<DietParameter> dietParameters = new HashSet<DietParameter>(0);
     private Set<MealLine> mealLines = new HashSet<MealLine>(0);

    public Meal() {
    }

	
    public Meal(String code, String name) {
        this.code = code;
        this.name = name;
    }
    public Meal(String code, String name, Set<DietParameter> dietParameters, Set<MealLine> mealLines) {
       this.code = code;
       this.name = name;
       this.dietParameters = dietParameters;
       this.mealLines = mealLines;
    }
   
    public long getMealId() {
        return this.mealId;
    }
    
    public void setMealId(long mealId) {
        this.mealId = mealId;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<DietParameter> getDietParameters() {
        return this.dietParameters;
    }
    
    public void setDietParameters(Set<DietParameter> dietParameters) {
        this.dietParameters = dietParameters;
    }
    public Set<MealLine> getMealLines() {
        return this.mealLines;
    }
    
    public void setMealLines(Set<MealLine> mealLines) {
        this.mealLines = mealLines;
    }




}


