package at.easydiet.model;
// Generated 06.04.2011 14:32:00 by Hibernate Tools 3.4.0.CR1



/**
 * NutrimentParameter generated by hbm2java
 */
public class NutrimentParameter  implements java.io.Serializable {


     private long nutrimentParameterId;
     private String value;
     private ParameterDefinition parameterDefinition;

    public NutrimentParameter() {
    }

    public NutrimentParameter(String value, ParameterDefinition parameterDefinition) {
       this.value = value;
       this.parameterDefinition = parameterDefinition;
    }
   
    public long getNutrimentParameterId() {
        return this.nutrimentParameterId;
    }
    
    public void setNutrimentParameterId(long nutrimentParameterId) {
        this.nutrimentParameterId = nutrimentParameterId;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public ParameterDefinition getParameterDefinition() {
        return this.parameterDefinition;
    }
    
    public void setParameterDefinition(ParameterDefinition parameterDefinition) {
        this.parameterDefinition = parameterDefinition;
    }




}


