package at.easydiet.model;
// Generated 06.04.2011 16:43:36 by Hibernate Tools 3.4.0.CR1



/**
 * ParameterDefinition generated by hbm2java
 */
public class ParameterDefinition  implements java.io.Serializable {


     private long parameterDefinitionId;
     private String name;
     private String unit;
     private String checkPattern;
     private ParameterDefinitionDataType type;

    public ParameterDefinition() {
    }

    public ParameterDefinition(String name, String unit, String checkPattern, ParameterDefinitionDataType type) {
       this.name = name;
       this.unit = unit;
       this.checkPattern = checkPattern;
       this.type = type;
    }
   
    public long getParameterDefinitionId() {
        return this.parameterDefinitionId;
    }
    
    public void setParameterDefinitionId(long parameterDefinitionId) {
        this.parameterDefinitionId = parameterDefinitionId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    public String getCheckPattern() {
        return this.checkPattern;
    }
    
    public void setCheckPattern(String checkPattern) {
        this.checkPattern = checkPattern;
    }
    public ParameterDefinitionDataType getType() {
        return this.type;
    }
    
    public void setType(ParameterDefinitionDataType type) {
        this.type = type;
    }




}


