package at.easydiet.model;
// Generated 06.04.2011 14:32:00 by Hibernate Tools 3.4.0.CR1


import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PatientState generated by hbm2java
 */
public class PatientState  implements java.io.Serializable {


     private long patientStateId;
     private Date date;
     private Clob anamnesis;
     private Integer weight;
     private float weightPercentile;
     private Integer height;
     private float heightPercentile;
     private int compliance;
     private int motivation;
     private PatientStateType type;
     private SystemUser creator;
     private Set<LaborReport> laborReports = new HashSet<LaborReport>(0);

    public PatientState() {
    }

	
    public PatientState(Date date, PatientStateType type, SystemUser creator) {
        this.date = date;
        this.type = type;
        this.creator = creator;
    }
    public PatientState(Date date, Clob anamnesis, Integer weight, float weightPercentile, Integer height, float heightPercentile, int compliance, int motivation, PatientStateType type, SystemUser creator, Set<LaborReport> laborReports) {
       this.date = date;
       this.anamnesis = anamnesis;
       this.weight = weight;
       this.weightPercentile = weightPercentile;
       this.height = height;
       this.heightPercentile = heightPercentile;
       this.compliance = compliance;
       this.motivation = motivation;
       this.type = type;
       this.creator = creator;
       this.laborReports = laborReports;
    }
   
    public long getPatientStateId() {
        return this.patientStateId;
    }
    
    public void setPatientStateId(long patientStateId) {
        this.patientStateId = patientStateId;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Clob getAnamnesis() {
        return this.anamnesis;
    }
    
    public void setAnamnesis(Clob anamnesis) {
        this.anamnesis = anamnesis;
    }
    public Integer getWeight() {
        return this.weight;
    }
    
    public void setWeight(Integer weight) {
        this.weight = weight;
    }
    public float getWeightPercentile() {
        return this.weightPercentile;
    }
    
    public void setWeightPercentile(float weightPercentile) {
        this.weightPercentile = weightPercentile;
    }
    public Integer getHeight() {
        return this.height;
    }
    
    public void setHeight(Integer height) {
        this.height = height;
    }
    public float getHeightPercentile() {
        return this.heightPercentile;
    }
    
    public void setHeightPercentile(float heightPercentile) {
        this.heightPercentile = heightPercentile;
    }
    public int getCompliance() {
        return this.compliance;
    }
    
    public void setCompliance(int compliance) {
        this.compliance = compliance;
    }
    public int getMotivation() {
        return this.motivation;
    }
    
    public void setMotivation(int motivation) {
        this.motivation = motivation;
    }
    public PatientStateType getType() {
        return this.type;
    }
    
    public void setType(PatientStateType type) {
        this.type = type;
    }
    public SystemUser getCreator() {
        return this.creator;
    }
    
    public void setCreator(SystemUser creator) {
        this.creator = creator;
    }
    public Set<LaborReport> getLaborReports() {
        return this.laborReports;
    }
    
    public void setLaborReports(Set<LaborReport> laborReports) {
        this.laborReports = laborReports;
    }




}


