package at.easydiet.model;
// Generated 06.04.2011 14:32:00 by Hibernate Tools 3.4.0.CR1


import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Patient generated by hbm2java
 */
public class Patient  implements java.io.Serializable {


     private long patientId;
     private String insuranceNumber;
     private String forename;
     private String lastname;
     private String title;
     private String street;
     private String zip;
     private String place;
     private String country;
     private Date birthday;
     private String job;
     private String religion;
     private String[] illnesses;
     private String regime;
     private Clob notice;
     private Gender gender;
     private Set<FamilyAnamnesis> familyanamnesis = new HashSet<FamilyAnamnesis>(0);
     private Set<PatientState> patientstate = new HashSet<PatientState>(0);
     private Set<LaborReport> laborReports = new HashSet<LaborReport>(0);
     private Set<DietTreatment> treatments = new HashSet<DietTreatment>(0);
     private Set<Recipe> disfavors = new HashSet<Recipe>(0);

    public Patient() {
    }

	
    public Patient(String insuranceNumber, String forename, String lastname, String title, String street, String zip, String place, String country, Date birthday, Gender gender) {
        this.insuranceNumber = insuranceNumber;
        this.forename = forename;
        this.lastname = lastname;
        this.title = title;
        this.street = street;
        this.zip = zip;
        this.place = place;
        this.country = country;
        this.birthday = birthday;
        this.gender = gender;
    }
    public Patient(String insuranceNumber, String forename, String lastname, String title, String street, String zip, String place, String country, Date birthday, String job, String religion, String[] illnesses, String regime, Clob notice, Gender gender, Set<FamilyAnamnesis> familyanamnesis, Set<PatientState> patientstate, Set<LaborReport> laborReports, Set<DietTreatment> treatments, Set<Recipe> disfavors) {
       this.insuranceNumber = insuranceNumber;
       this.forename = forename;
       this.lastname = lastname;
       this.title = title;
       this.street = street;
       this.zip = zip;
       this.place = place;
       this.country = country;
       this.birthday = birthday;
       this.job = job;
       this.religion = religion;
       this.illnesses = illnesses;
       this.regime = regime;
       this.notice = notice;
       this.gender = gender;
       this.familyanamnesis = familyanamnesis;
       this.patientstate = patientstate;
       this.laborReports = laborReports;
       this.treatments = treatments;
       this.disfavors = disfavors;
    }
   
    public long getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(long patientId) {
        this.patientId = patientId;
    }
    public String getInsuranceNumber() {
        return this.insuranceNumber;
    }
    
    public void setInsuranceNumber(String insuranceNumber) {
        this.insuranceNumber = insuranceNumber;
    }
    public String getForename() {
        return this.forename;
    }
    
    public void setForename(String forename) {
        this.forename = forename;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }
    public String getPlace() {
        return this.place;
    }
    
    public void setPlace(String place) {
        this.place = place;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public String getJob() {
        return this.job;
    }
    
    public void setJob(String job) {
        this.job = job;
    }
    public String getReligion() {
        return this.religion;
    }
    
    public void setReligion(String religion) {
        this.religion = religion;
    }
    public String[] getIllnesses() {
        return this.illnesses;
    }
    
    public void setIllnesses(String[] illnesses) {
        this.illnesses = illnesses;
    }
    public String getRegime() {
        return this.regime;
    }
    
    public void setRegime(String regime) {
        this.regime = regime;
    }
    public Clob getNotice() {
        return this.notice;
    }
    
    public void setNotice(Clob notice) {
        this.notice = notice;
    }
    public Gender getGender() {
        return this.gender;
    }
    
    public void setGender(Gender gender) {
        this.gender = gender;
    }
    public Set<FamilyAnamnesis> getFamilyanamnesis() {
        return this.familyanamnesis;
    }
    
    public void setFamilyanamnesis(Set<FamilyAnamnesis> familyanamnesis) {
        this.familyanamnesis = familyanamnesis;
    }
    public Set<PatientState> getPatientstate() {
        return this.patientstate;
    }
    
    public void setPatientstate(Set<PatientState> patientstate) {
        this.patientstate = patientstate;
    }
    public Set<LaborReport> getLaborReports() {
        return this.laborReports;
    }
    
    public void setLaborReports(Set<LaborReport> laborReports) {
        this.laborReports = laborReports;
    }
    public Set<DietTreatment> getTreatments() {
        return this.treatments;
    }
    
    public void setTreatments(Set<DietTreatment> treatments) {
        this.treatments = treatments;
    }
    public Set<Recipe> getDisfavors() {
        return this.disfavors;
    }
    
    public void setDisfavors(Set<Recipe> disfavors) {
        this.disfavors = disfavors;
    }




}


