package at.easydiet.model;
// Generated 06.04.2011 14:32:00 by Hibernate Tools 3.4.0.CR1



/**
 * PlanType generated by hbm2java
 */
public class PlanType  implements java.io.Serializable {


     private String name;

    public PlanType() {
    }

    public PlanType(String name) {
       this.name = name;
    }
   
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


