package at.easydiet.model;
// Generated 06.04.2011 16:43:36 by Hibernate Tools 3.4.0.CR1



/**
 * SystemUserFunction generated by hbm2java
 */
public class SystemUserFunction  implements java.io.Serializable {


     private String name;

    public SystemUserFunction() {
    }

    public SystemUserFunction(String name) {
       this.name = name;
    }
   
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


