package at.easydiet.model;
// Generated 06.04.2011 14:32:00 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TimeSpan generated by hbm2java
 */
public class TimeSpan  implements java.io.Serializable {


     private long timeSpanId;
     private Date start;
     private int duration;
     private Set<DietParameter> dietParameters = new HashSet<DietParameter>(0);
     private Set<Meal> meals = new HashSet<Meal>(0);

    public TimeSpan() {
    }

	
    public TimeSpan(Date start, int duration) {
        this.start = start;
        this.duration = duration;
    }
    public TimeSpan(Date start, int duration, Set<DietParameter> dietParameters, Set<Meal> meals) {
       this.start = start;
       this.duration = duration;
       this.dietParameters = dietParameters;
       this.meals = meals;
    }
   
    public long getTimeSpanId() {
        return this.timeSpanId;
    }
    
    public void setTimeSpanId(long timeSpanId) {
        this.timeSpanId = timeSpanId;
    }
    public Date getStart() {
        return this.start;
    }
    
    public void setStart(Date start) {
        this.start = start;
    }
    public int getDuration() {
        return this.duration;
    }
    
    public void setDuration(int duration) {
        this.duration = duration;
    }
    public Set<DietParameter> getDietParameters() {
        return this.dietParameters;
    }
    
    public void setDietParameters(Set<DietParameter> dietParameters) {
        this.dietParameters = dietParameters;
    }
    public Set<Meal> getMeals() {
        return this.meals;
    }
    
    public void setMeals(Set<Meal> meals) {
        this.meals = meals;
    }




}


